# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: true
  JavaScript: true
exclude_paths:
  - "lib/assets"
  # code climate complains a bunch about our toolkit.css -- is it useful to validate our CSS?
  - "app/assets/stylesheets"
  - "refresh.sh"
  - "app/javascript/__tests__"
checks:
  method-complexity:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 50
