# Save as .codeclimate.yml (note leading .) in project root directory
version: "2"
languages:
  Ruby: true
  JavaScript: true
exclude_patterns:
  - "lib/assets"
  # code climate complains a bunch about our toolkit.css -- is it useful to validate our CSS?
  - "app/assets/stylesheets"
  - "refresh.sh"
  - "app/javascript/__tests__"
checks:
  method-complexity:
    config:
      threshold: 8
  method-lines:
    config:
      threshold: 40
plugins:
 duplication:
   enabled: true
   config:
     count_threshold: 3