---
http_interactions:
- request:
    method: post
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/oauth2/token"
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.17.6
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 30 Mar 2023 15:34:19 GMT
      Set-Cookie:
      - BrowserId=VqMdC88QEe2TeH0FQL4pXA; domain=.salesforce.com; path=/; expires=Fri,
        29-Mar-2024 15:34:19 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:19 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:19
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://test.salesforce.com/id/00D8H0000004dNlUAI/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1680190459930","signature":"eyIACOrGGUBIFuFE5iOe8LnS/BkiD24RaMcHnUv5BPo="}'
  recorded_at: Thu, 30 Mar 2023 15:34:19 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm/list/0030P000020bdxYQAQ"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.6
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 30 Mar 2023 15:34:20 GMT
      Set-Cookie:
      - BrowserId=VtQX088QEe2ETjWzqJMcFw; domain=.salesforce.com; path=/; expires=Fri,
        29-Mar-2024 15:34:20 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:20 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:20
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '[{"totalMonthlyRent":null,"status":"Submitted","shortFormPreferences":[],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"raceEthnicity":null,"race":null,"primaryLanguage":"Not
        Listed","preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","pacificIslanderOther":null,"otherLanguage":"other
        language","noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Dolendo","isVeteran":null,"indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":"other
        gender","gender":"Not Listed","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","DALPCertified":null,"contactId":"0030P000020bdxYQAQ","city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null},"otherHousingCounselingAgency":null,"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0WU000000ClNXGMA3","lendingAgent":null,"isVeteranInHousehold":false,"isPrimaryApplicantVeteran":null,"isNonPrimaryMemberVeteran":null,"isFirstTimeHomebuyer":false,"id":"a0o0P00000FEUwHQAX","housingCounselingAgency":null,"householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","raceEthnicity":null,"race":null,"primaryLanguage":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"pacificIslanderOther":null,"otherLanguage":null,"noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Kanobi","isVeteran":null,"indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","DALPCertified":null,"contactId":null,"city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Household
        Member","appMemberId":"a0n8H000000t54zQAA","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null}],"homebuyerEducationAgency":null,"hasSenior":null,"hasPublicHousing":null,"hasMinimumCreditScore":false,"hasMilitaryService":null,"hasLoanPreapproval":false,"hasDisability":null,"hasDevelopmentalDisability":null,"hasCompletedHomebuyerEducation":false,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":null,"appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}]'
  recorded_at: Thu, 30 Mar 2023 15:34:20 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/ListingDetails?ids=a0WU000000ClNXGMA3&subset=browse"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.17.6
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 30 Mar 2023 15:34:20 GMT
      Set-Cookie:
      - BrowserId=VzLZqM8QEe2lEcVWgDxlSg; domain=.salesforce.com; path=/; expires=Fri,
        29-Mar-2024 15:34:20 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:20 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Fri, 29-Mar-2024 15:34:20
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '[{"unitSummaries":{"reserved":null,"general":[{"unitType":"Studio","totalUnits":1,"minSquareFt":476,"minRentalMinIncome":2477.50,"minPriceWithParking":null,"minPriceWithoutParking":null,"minPercentIncome":null,"minOccupancy":1,"minMonthlyRent":991.00,"minHoaDuesWithParking":null,"minHoaDuesWithoutParking":null,"maxSquareFt":476,"maxRentalMinIncome":2477.50,"maxPriceWithParking":null,"maxPriceWithoutParking":null,"maxPercentIncome":null,"maxOccupancy":2,"maxMonthlyRent":991.00,"maxHoaDuesWithParking":null,"maxHoaDuesWithoutParking":null,"listingID":"a0WU000000ClNXGMA3","availability":null,"absoluteMinIncome":null,"absoluteMaxIncome":null}]},"reservedDescriptor":null,"prioritiesDescriptor":null,"listingID":"a0WU000000ClNXGMA3","listing":{"attributes":{"type":"Listing__c","url":"/services/data/v35.0/sobjects/Listing__c/a0WU000000ClNXGMA3"},"Id":"a0WU000000ClNXGMA3","Tenure__c":"Re-rental","Name":"8
        Tenth (NEMA) Unit 742","Lottery_Results_Date__c":"2016-06-10","Reserved_community_minimum_age__c":0,"hasWaitlist__c":false,"Units_Available__c":0,"Building_URL__c":"http://sfmohcd.org/sites/default/files/Documents/MOH/Housing%20Listing%20Photos/NEMA8-10thSt.jpg","Building_Name__c":"NEMA
        Phase 1","Building_Street_Address__c":"8 10th St","Building_City__c":"San
        Francisco","Building_State__c":"CA","Building_Zip_Code__c":"94103","Publish_Lottery_Results__c":false},"chartTypes":null}]'
  recorded_at: Thu, 30 Mar 2023 15:34:21 GMT
recorded_with: VCR 6.1.0
