---
http_interactions:
- request:
    method: post
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/oauth2/token"
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 08 Mar 2024 21:47:40 GMT
      Set-Cookie:
      - BrowserId=fMONZ92VEe6ITjlH8ZFWaA; domain=.salesforce.com; path=/; expires=Sat,
        08-Mar-2025 21:47:40 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:40 GMT; Max-Age=31536000;
        secure
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:40
        GMT; Max-Age=31536000; secure
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://test.salesforce.com/id/00D8H0000004dNlUAI/0050P000007QAY9QAO","token_type":"Bearer","issued_at":"1709934460935","signature":"ryEnhTT67eSvQcFXoaMIyQhaXs0DDAuKAHDeusjQmtY="}'
  recorded_at: Fri, 08 Mar 2024 21:47:40 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm/a0o0P00000FEUwHQAX"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v2.7.4
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 08 Mar 2024 21:47:41 GMT
      Set-Cookie:
      - BrowserId=fQQ_2N2VEe6KEaf99_pVTQ; domain=.salesforce.com; path=/; expires=Sat,
        08-Mar-2025 21:47:41 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:41 GMT; Max-Age=31536000;
        secure
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:41
        GMT; Max-Age=31536000; secure
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Draft","shortFormPreferences":[],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"raceEthnicity":null,"race":null,"primaryLanguage":"Not
        Listed","preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","pacificIslanderOther":null,"otherLanguage":"other
        language","noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Dolendo","jobClassification":null,"isVeteran":null,"isSFUSDEmployee":"No","indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":"other
        gender","gender":"Not Listed","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","DALPCertified":null,"contactId":"0030P000020bdxYQAQ","city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null},"otherHousingCounselingAgency":null,"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0WU000000ClNXGMA3","lendingAgent":null,"jobClassification":null,"isVeteranInHousehold":false,"isSFUSDEmployee":"No","isPrimaryApplicantVeteran":null,"isNonPrimaryMemberVeteran":null,"isFirstTimeHomebuyer":false,"id":"a0o0P00000FEUwHQAX","housingCounselingAgency":null,"householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","raceEthnicity":null,"race":null,"primaryLanguage":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"pacificIslanderOther":null,"otherLanguage":null,"noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Kanobi","jobClassification":null,"isVeteran":null,"isSFUSDEmployee":"No","indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","DALPCertified":null,"contactId":null,"city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Household
        Member","appMemberId":"a0n8H000000t54zQAA","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null}],"homebuyerEducationAgency":null,"hasSenior":null,"hasPublicHousing":null,"hasMinimumCreditScore":false,"hasMilitaryService":null,"hasLoanPreapproval":false,"hasDisability":null,"hasDevelopmentalDisability":null,"hasCompletedHomebuyerEducation":false,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":null,"appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}'
  recorded_at: Fri, 08 Mar 2024 21:47:41 GMT
- request:
    method: post
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/shortForm"
    body:
      encoding: UTF-8
      string: '{"id":"a0o0P00000FEUwHQAX","primaryApplicant":{"phone":"2222222222","firstName":"Christine","lastName":"Dolendo","phoneType":"Home","alternatePhone":null,"alternatePhoneType":null,"gender":"Not
        Listed","genderOther":"other gender","primaryLanguage":"Not Listed","otherLanguage":"other
        language","dob":"1990-2-2","contactId":"0030P000020bdxYQAQ","webAppID":1},"householdMembers":[{"firstName":"Obie","lastName":"Kanobi","relationship":"Spouse","dob":"1990-7-23"}],"listingID":"a0WU000000ClNXGMA3","referral":"","annualIncome":"20000","applicationSubmissionType":"Electronic","applicationSubmittedDate":"2016-09-07","status":"Draft"}'
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/json
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 08 Mar 2024 21:47:41 GMT
      Set-Cookie:
      - BrowserId=fWIXpt2VEe673t1S7_mqPA; domain=.salesforce.com; path=/; expires=Sat,
        08-Mar-2025 21:47:41 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:41 GMT; Max-Age=31536000;
        secure
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Sat, 08-Mar-2025 21:47:41
        GMT; Max-Age=31536000; secure
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalMonthlyRent":null,"status":"Draft","shortFormPreferences":[],"referral":null,"primaryApplicant":{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":"1","state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":null,"raceEthnicity":null,"race":null,"primaryLanguage":"Not
        Listed","preferenceAddressMatch":null,"phoneType":"Home","phone":"2222222222","pacificIslanderOther":null,"otherLanguage":"other
        language","noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Dolendo","jobClassification":null,"isVeteran":null,"isSFUSDEmployee":"No","indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":"other
        gender","gender":"Not Listed","firstName":"Christine","ethnicity":null,"email":null,"DOB":"1990-02-02","DALPCertified":null,"contactId":"0030P000020bdxYQAQ","city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Primary
        Applicant","appMemberId":"a0n0P00000AwpInQAJ","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null},"otherHousingCounselingAgency":null,"name":"APP-00038758","monthlyIncome":null,"lotteryNumberManual":null,"lotteryNumber":"00038758","listingID":"a0WU000000ClNXGMA3","lendingAgent":null,"jobClassification":null,"isVeteranInHousehold":false,"isSFUSDEmployee":"No","isPrimaryApplicantVeteran":null,"isNonPrimaryMemberVeteran":null,"isFirstTimeHomebuyer":false,"id":"a0o0P00000FEUwHQAX","housingCounselingAgency":null,"householdVouchersSubsidies":null,"householdMembers":[{"zip":null,"yCoordinate":null,"xCoordinate":null,"workInSf":null,"whiteOther":null,"whichComponentOfLocatorWasUsed":null,"webAppID":null,"state":null,"sexualOrientationOther":null,"sexualOrientation":null,"sexAtBirth":null,"relationship":"Spouse","raceEthnicity":null,"race":null,"primaryLanguage":null,"preferenceAddressMatch":null,"phoneType":null,"phone":null,"pacificIslanderOther":null,"otherLanguage":null,"noPhone":false,"noEmail":false,"noAddress":false,"MLSId":null,"middleName":null,"menaOther":null,"MCCCertified":null,"mailingZip":null,"mailingState":null,"mailingCity":null,"mailingAddress":null,"lendingAgentStatus":null,"latinoOther":null,"lastName":"Kanobi","jobClassification":null,"isVeteran":null,"isSFUSDEmployee":"No","indigenousOther":null,"indigenousNativeAmericanGroup":null,"indigenousCentralSouthAmericaGroup":null,"hiv":false,"hasSameAddressAsApplicant":null,"hasDisability":null,"hasAltMailingAddress":false,"genderOther":null,"gender":null,"firstName":"Obie","ethnicity":null,"email":null,"DOB":"1990-07-23","DALPCertified":null,"contactId":null,"city":null,"candidateScore":null,"BMRCertified":null,"blackOther":null,"asianOther":null,"appMemberType":"Household
        Member","appMemberId":"a0n8H000000t54zQAA","alternatePhoneType":null,"alternatePhone":null,"alternateContactTypeOther":null,"alternateContactType":null,"agency":null,"address":null,"accountId":null,"acceptingNewMOHCDClients":null}],"homebuyerEducationAgency":null,"hasSenior":null,"hasPublicHousing":null,"hasMinimumCreditScore":false,"hasMilitaryService":null,"hasLoanPreapproval":false,"hasDisability":null,"hasDevelopmentalDisability":null,"hasCompletedHomebuyerEducation":false,"formMetadata":null,"externalSessionId":"","didApplicantUseHousingCounselingAgency":null,"appRTType":"Rental_Short_Form","applicationSubmittedDate":"2016-09-07","applicationSubmissionType":"Electronic","applicationLanguage":"English","answeredCommunityScreening":null,"annualIncome":20000.00,"alternateContact":null,"agreeToTerms":false,"adaPrioritiesSelected":null}'
  recorded_at: Fri, 08 Mar 2024 21:47:43 GMT
recorded_with: VCR 6.1.0
