import { stripMostTags } from "../../util/filterUtil"

describe("languageUtil", () => {
  describe("stripMostTags", () => {
    it("strips and html string of all tags and attributes except <a>'s and <p>'s and <br>'s", () => {
      const stripped = stripMostTags(
        '<p><span style="font-family: Arial, sans-serif; font-size: 10pt;">All BMR renters must review and acknowledge the </span><a href="https://sfmohcd.org/sites/default/files/Documents/MOH/Inclusionary%20Manuals/Inclusionary%20Affordable%20Housing%20Program%20Manual%2010.15.2018.pdf" target="_blank" style="font-family: Arial, sans-serif; font-size: 10pt;">Inclusionary Affordable Housing Program Monitoring and Procedures Manual 2018</a><span style="font-family: Arial, sans-serif; font-size: 10pt;"> that governs this property upon the signing of a lease for a BMR unit.</span></p><p><span style="font-size: 10.5pt;"> </span></p><p><span style="font-family: Arial, sans-serif; font-size: 10pt;">Applicants should be informed that BMR rental units in some buildings may convert to ownership units in the future. In the case of conversion, BMR renters will be afforded certain rights as explained in the </span><a href="https://sfmohcd.org/sites/default/files/Documents/MOH/Inclusionary%20Manuals/Inclusionary%20Affordable%20Housing%20Program%20Manual%2010.15.2018.pdf" target="_blank">Inclusionary Affordable Housing Program Monitoring and Procedures Manual 2018.</a> Applicants should inquire with the building contact person listed above to determine if the building has a minimum number of years that it must remain a rental building. (Some buildings may have such restrictions based on government sources of financing for their building.) Most buildings may have no restrictions on conversion at all.</p><p><span style="font-size: 10.5pt;"> </span></p><p><span style="font-family: Arial, sans-serif; font-size: 10pt;">It is also important to note that units governed by the Inclusionary Housing Program are NOT governed by the San Francisco Rent Ordinance (also known as “rent control”). Among other rules, rents may increase beyond increases allowed under “rent control.” Please see the </span><a href="https://sfmohcd.org/sites/default/files/Documents/MOH/Inclusionary%20Manuals/Inclusionary%20Affordable%20Housing%20Program%20Manual%2010.15.2018.pdf" target="_blank" style="font-family: Arial, sans-serif; font-size: 10pt;">Inclusionary Affordable Housing Program Monitoring and Procedures Manual 2018</a><span style="font-family: Arial, sans-serif; font-size: 10pt;"> for more information.</span></p><p><br></p>'
      )
      expect(stripped).toEqual(expect.not.stringMatching(/<span>/))
    })
  })
})
