default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default
  database: sf_dahlia

test:
  <<: *default
  database: sf_dahlia_test
