AddModelVirtualAttributeCheck: {}
AlwaysAddDbIndexCheck: {}
#CheckSaveReturnValueCheck: { }
DefaultScopeIsEvilCheck: {}
DryBundlerInCapistranoCheck: {}
HashSyntaxCheck: {}
IsolateSeedDataCheck: {}
KeepFindersOnTheirOwnModelCheck: {}
LawOfDemeterCheck: {}
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: {}
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: {}
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: {}
NotUseDefaultRouteCheck: {}
NotUseTimeAgoInWordsCheck: {}
OveruseRouteCustomizationsCheck: {}
ProtectMassAssignmentCheck: {}
RemoveEmptyHelpersCheck: {}
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: {}
RemoveUnusedMethodsInControllersCheck:
  {
    except_methods:
      [
        "Overrides::SessionsController#render_create_success",
        "Overrides::TokenValidationsController#render_validate_token_success",
        "Overrides::RegistrationsController#render_create_success",
        "Overrides::RegistrationsController#error_checks_for_create",
        "Overrides::SessionsController#render_create_error_not_confirmed",
        "Overrides::SessionsController#render_create_error_bad_credentials",
        "Overrides::PasswordsController#render_edit_error",
        "Overrides::PasswordsController#edit",
        "Overrides::PasswordsController#resource_update_method",
        "Overrides::PasswordsController#render_update_success",
        "Overrides::RegistrationsController#account_update_params",
        "ListingController#use_react_app",
        "AuthController#sign_in",
        "SitemapsController#generate",
      ],
  }
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck:
  { except_methods: ["User#email_changed?", "User#send_devise_notification"] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: {}
RestrictAutoGeneratedRoutesCheck: {}
SimplifyRenderInControllersCheck: {}
SimplifyRenderInViewsCheck: {}
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: {}
# UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
UseParenthesesInMethodDefCheck: {}
UseObserverCheck: {}
UseQueryAttributeCheck: {}
UseSayWithTimeInMigrationsCheck: {}
UseScopeAccessCheck: {}
UseTurboSprocketsRails3Check: {}
