---
# Set timeout to 25 to take advantage of the default 30 second Heroku shutdown timeout.
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
:queues:
  - default
  - mailers

# you can override concurrency based on environment
production:
  :concurrency: 5
development:
  :verbose: true
  :concurrency: 1
