module ServiceHelper
  SALESFORCE_LISTING_FIELD_NAMES_TO_TRANSLATE = %w[
    Accessibility__c
    Amenities__c
    Appliances__c
    Costs_Not_Included__c
    Credit_Rating__c
    Legal_Disclaimers__c
    Leasing_Agent_Title__c
    Listing_Other_Notes__c
    Lottery_Summary__c
    Lottery_Venue__c
    Office_Hours__c
    Parking_Information__c
    Pet_Policy__c
    Eviction_History__c
    Required_Documents__c
    Reserved_community_type_Description__c
    Services_Onsite__c
    Smoking_Policy__c
    Utilities__c
    Realtor_Commission_Info__c
    Repricing_Mechanism__c
  ].freeze
  LISTING_FIELD_NAMES_TO_TRANSLATE = %w[
    Accessibility
    Amenities
    Appliances
    Costs_Not_Included
    Credit_Rating
    Legal_Disclaimers
    Leasing_Agent_Title
    Listing_Other_Notes
    Lottery_Summary
    Lottery_Venue
    Office_Hours
    Parking_Information
    Pet_Policy
    Eviction_History
    Required_Documents
    Reserved_community_type_Description
    Services_Onsite
    Smoking_Policy
    Utilities
    Realtor_Commission_Info
    Repricing_Mechanism
  ].freeze
end
