###*
# @license Angulartics v0.19.2
# (c) 2013 Luis Farzati http://luisfarzati.github.io/angulartics
# Google Tag Manager Plugin Contributed by http://github.com/danrowe49
# License: MIT
# -- modified by Exygy for DAHLIA project --
###

do (angular) ->
  'use strict'

  ###*
  # @ngdoc overview
  # @name angulartics.google.analytics
  # Enables analytics support for Google Tag Manager (http://google.com/tagmanager)
  ###

  angular.module('angulartics.google.tagmanager', [ 'angulartics' ]).config [
    '$analyticsProvider'
    ($analyticsProvider) ->
      $analyticsProvider.settings.ga = userId: null

      ###*
      # Send content views to the dataLayer
      #
      # @param {string} path Required 'content name' (string) describes the content loaded
      ###

      $analyticsProvider.registerPageTrack (path) ->
        dataLayer = window.dataLayer = window.dataLayer or []
        dataLayer.push
          'event': 'Page View'
          'label': path
          # 'userId': $analyticsProvider.settings.ga.userId
        return

      ###*
      # Send interactions to the dataLayer, i.e. for event tracking in Google Tag Manager
      # @name eventTrack
      #
      # @param {string} event (required)
      # @param {object} properties Comprised of the mandatory field 'category' (string) and optional  fields
      ###

      $analyticsProvider.registerEventTrack (event, properties) ->
        dataLayer = window.dataLayer = window.dataLayer or []
        properties = properties or {}
        dataLayer.push
          'event': event
          'category': properties.category
          'action': properties.action
          'label': properties.label
          'value': properties.value
          # 'interaction-type': properties.noninteraction
          # 'userId': $analyticsProvider.settings.ga.userId
        return

      ###*
      # Set userId for use with Universal Analytics User ID feature
      # @name setUsername
      #
      # @param {string} userId Required 'userId' value (string) used to identify user cross-device in Google Analytics
      ###

      $analyticsProvider.registerSetUsername (userId) ->
        $analyticsProvider.settings.ga.userId = userId
        return
      return
  ]
  return

# ---
# generated by js2coffee 2.2.0
