name: Heroku
on:
  pull_request:
    types: [opened, synchronize, closed, reopened, labeled]

jobs:
  create-review-app:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || || github.event.label.name == 'heroku-review-app'
    runs-on: ubuntu-latest
    steps:
      - uses: fastruby/manage-heroku-review-app@v1.2
        with:
          action: create
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
          GITHUB_TOKEN: ${{ github.token }}

  destroy-review-app:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: fastruby/manage-heroku-review-app@v1.2
        with:
          action: destroy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
          GITHUB_TOKEN: ${{ github.token }}